services:
  - type: web
    name: library-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-mongo.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app,https://your-frontend-domain.netlify.app
